name: CI # Name of the workflow

on:   # everytime someone make a pull request to master branch or pushes code to master branch this event is    triggered 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:  # only 1 job is running

  test: # job name

    name: Test on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x] # can be [12.x, 14.x, 15.x, 16.x]
        os: [ubuntu-latest]  # can be [ubuntu-latest, windows-latest, macos-latest]

    steps: # bring source code into ubuntu machine / cwd
    - uses: actions/checkout@v2 # checkout to the current branch
    - uses: actions/setup-node@v1 # setup nodejs V1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install # installs all the dependencies ( clean-install)
      run: npm ci 
    - name: npm test # unit testing using jest lib in js
      run npm test
  
  # publish: 
  #   needs: test => to run the publish job the test job should execute first , each job is assigned differet servers

# steps : can run commands , setup tasks or run an action
# uses : selects an action
# run : runs a command line argument

#  matrix is used when we are using multiple OS / or multiple versions of appliation
